name: Upstream LSHW testing

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Fetch upstream LSHW
      run: |
        git clone https://ezix.org/src/pkg/lshw.git
    - name: Compile LSHW
      run: |
        pushd lshw
        make DATADIR=$(readlink -f src)
        popd
    - name: Compile LSHW tests
      run: |
        make
    - name: Execute LSHW tests
      run: |
        LSHW=./lshw/src/lshw ./run-tests.sh
  
